### ISSUE TITLE
Link to repo incorrect in timeline view

### ISSUE THREAD

**Issue by oandregal** [youknowriad/codehealth#15]
In looking at the [existing WordPress dashboard](https://www.codevitals.run/project/wordpress), I wanted to visit the Github link of the last commit. Instead, I was redirected to the gutenberg repository, where the commit sha doesn't exist.

Steps:

- Go to the WordPress dashboard https://www.codevitals.run/project/wordpress
- Click any point/commit in the timeline view.
- In the pop-up that shows up, click in the commit SHA.

![image](https://user-images.githubusercontent.com/583546/234616727-ec50a814-021d-43d9-b636-3d8d570744e4.png)

I expected the link to take me to the wordpress-develop repository (the source for this dashboard, as far as I'm aware). Instead it took me to the gutenberg repository, in which the commit does not exist.

- Link provide (bad): https://github.com/WordPress/gutenberg/commit/7e1e0005ad9a0725b24a5cb8d8b59627c2bae580
- Link that should have been provided (good): https://github.com/WordPress/wordpress-develop/commit/7e1e0005ad9a0725b24a5cb8d8b59627c2bae580

**Comment by youknowriad** [comment]
Right 👍 we need to have a config for a url per project 👍

**Comment by felixarntz** [comment]
Just ran into this bug as well. How complex is it to add the repository name (vendor + name) to each project? Alternatively, a short-term workaround would be to at least "expand" the hard-coding approach in https://github.com/youknowriad/codevitals/blob/main/pages/project/%5Bproject_slug%5D/index.js#L284, to use either `WordPress/gutenberg` or `WordPress/wordpress-develop` conditionally based on project slug.
